//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordAudioStream.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordAudioStream.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap move {
            get {
                object obj = ResourceManager.GetObject("move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NAudio {
            get {
                object obj = ResourceManager.GetObject("NAudio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap resize {
            get {
                object obj = ResourceManager.GetObject("resize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SharpDX {
            get {
                object obj = ResourceManager.GetObject("SharpDX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SharpDX_Direct3D11 {
            get {
                object obj = ResourceManager.GetObject("SharpDX_Direct3D11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SharpDX_DXGI {
            get {
                object obj = ResourceManager.GetObject("SharpDX_DXGI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When streaming a specific window, if the window is closed, this program will also close.
        ///This will trigger the Discord stream to end automatically..
        /// </summary>
        internal static string Tooltip_AutoExit {
            get {
                return ResourceManager.GetString("Tooltip_AutoExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate cap for captured video. Keep in mind that users without
        ///Discord Nitro cannot stream video at more than 30 FPS..
        /// </summary>
        internal static string Tooltip_CaptureFramerate {
            get {
                return ResourceManager.GetString("Tooltip_CaptureFramerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture method when capturing an entire monitor (see docs/CaptureMethods.md)..
        /// </summary>
        internal static string Tooltip_FullscreenMethod {
            get {
                return ResourceManager.GetString("Tooltip_FullscreenMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure the video is streamed correctly, even if the DiscordAudioStream window is partially off-screen.
        ///May increase CPU usage (and can make the window unresponsive in high frame rates)..
        /// </summary>
        internal static string Tooltip_OffscreenDraw {
            get {
                return ResourceManager.GetString("Tooltip_OffscreenDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log most actions taken inside the program to help find bugs and crashes.
        ///The log is written to a file called DiscordAudioStream_log.txt (see readme)..
        /// </summary>
        internal static string Tooltip_OutputLog {
            get {
                return ResourceManager.GetString("Tooltip_OutputLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture method when capturing a specific window (see docs/CaptureMethods.md)..
        /// </summary>
        internal static string Tooltip_WindowMethod {
            get {
                return ResourceManager.GetString("Tooltip_WindowMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/p-rivero.
        /// </summary>
        internal static string URL_AuthorLink {
            get {
                return ResourceManager.GetString("URL_AuthorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/p-rivero/DiscordAudioStream/issues.
        /// </summary>
        internal static string URL_IssuesLink {
            get {
                return ResourceManager.GetString("URL_IssuesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/p-rivero/DiscordAudioStream/blob/master/LICENSE.
        /// </summary>
        internal static string URL_LicenseLink {
            get {
                return ResourceManager.GetString("URL_LicenseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/ModuleArt.
        /// </summary>
        internal static string URL_ModuleArtLink {
            get {
                return ResourceManager.GetString("URL_ModuleArtLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/p-rivero/DiscordAudioStream.
        /// </summary>
        internal static string URL_ProjectLink {
            get {
                return ResourceManager.GetString("URL_ProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/ModuleArt/quick-screen-recorder.
        /// </summary>
        internal static string URL_ScreenRecorderLink {
            get {
                return ResourceManager.GetString("URL_ScreenRecorderLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/p-rivero/DiscordAudioStream/releases.
        /// </summary>
        internal static string URL_UpdatesLink {
            get {
                return ResourceManager.GetString("URL_UpdatesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_about {
            get {
                object obj = ResourceManager.GetObject("white_about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_mixer {
            get {
                object obj = ResourceManager.GetObject("white_mixer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_ontop {
            get {
                object obj = ResourceManager.GetObject("white_ontop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_preview {
            get {
                object obj = ResourceManager.GetObject("white_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_record {
            get {
                object obj = ResourceManager.GetObject("white_record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_refresh {
            get {
                object obj = ResourceManager.GetObject("white_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_settings {
            get {
                object obj = ResourceManager.GetObject("white_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_speaker {
            get {
                object obj = ResourceManager.GetObject("white_speaker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_stop {
            get {
                object obj = ResourceManager.GetObject("white_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
