// <auto-generated>
//   Annotate this file as auto-generated to suppress warnings of static analyzers.
// </auto-generated>

namespace System.Runtime.CompilerServices;

// See https://stackoverflow.com/questions/65663172/is-is-possible-to-use-library-with-c-sharp-9-records-in-net-framework-4-x

internal class IsExternalInit { }
