using CustomComponents;
using System;
using System.Windows.Forms;
using System.Reflection;
using System.Resources;
using DLLs;

namespace DiscordAudioStream
{
	static class Program
	{
		[STAThread]
		static void Main(string[] args)
		{
			AppDomain.CurrentDomain.AssemblyResolve += new ResolveEventHandler(CurrentDomain_AssemblyResolve);
			User32.SetProcessDpiAwarenessContext(User32.DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);

			Application.EnableVisualStyles();
			Application.SetCompatibleTextRenderingDefault(false);

			Application.ThreadException += ApplicationThreadException;
			// Set the unhandled exception mode to force all Windows Forms errors to go through our handler.
			Application.SetUnhandledExceptionMode(UnhandledExceptionMode.CatchException);
			AppDomain.CurrentDomain.UnhandledException += CurrentDomainUnhandledException;



			bool darkMode;
			int theme = Properties.Settings.Default.Theme;
			if (theme == 0)
			{
				darkMode = DarkThemeManager.IsDarkTheme();
			}
			else if (theme == 1)
			{
				darkMode = false;
			}
			else
			{
				darkMode = true;
			}

			if (darkMode)
			{
				Uxtheme.AllowDarkModeForApp(true);
			}

			MainForm mainForm = new MainForm(darkMode);
			Application.Run(mainForm);
		}


		private static Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
		{
			string dllName = args.Name.Contains(",") ? args.Name.Substring(0, args.Name.IndexOf(',')) : args.Name.Replace(".dll", "");

			dllName = dllName.Replace(".", "_");

			if (dllName.EndsWith("_resources")) return null;

			ResourceManager rm = new ResourceManager(MethodBase.GetCurrentMethod().DeclaringType.Namespace + ".Properties.Resources", Assembly.GetExecutingAssembly());

			byte[] bytes = (byte[])rm.GetObject(dllName);

			return Assembly.Load(bytes);
		}

		private static void CurrentDomainUnhandledException(object sender, UnhandledExceptionEventArgs e)
		{
			HandleException(e.ExceptionObject as Exception);
		}
		private static void ApplicationThreadException(object sender, System.Threading.ThreadExceptionEventArgs e)
		{
			HandleException(e.Exception);
		}
		private static void HandleException(Exception exception)
		{
			const string PATH = "stack_trace.txt";

			string[] lines = new string[] { exception.ToString() };
			System.IO.File.WriteAllLines(PATH, lines);

			string msg = "Caught exception: " + exception.Message + "\n";
			msg += "Check the autogenerated " + PATH + " file:\n";
			msg += System.IO.Path.GetFullPath(PATH);
			MessageBox.Show(msg, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);

			throw exception;
		}

	}
}
